name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  resource_group_name: rg-githubactions
  location: "Australia East"
  subscriptionId: d64eef0e-d7f1-4c6c-bf8a-9989e7483dd7    

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name}}
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscription-id: ${{ env.subscriptionId }}
          region: "${{ env.location }}"          
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourceGroupName=${{ env.resource_group_name}}
            location=${{ env.location }}
          deploymentName: ${{ env.resource_group_name}}
 
      - name: Deploy Storage accountt stgithubactions
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name}}
          subscription-id: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globostg0432catene2
            location=${{ env.location }}
          deploymentMode: Incremental

      - name: Deploy VM
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name}}
          subscription-id: ${{ env.subscriptionId }}
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location=${{ env.location }}
          deploymentMode: Incremental