name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-GitHubActions
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscription-id: d64eef0e-d7f1-4c6c-bf8a-9989e7483dd7
          region: Australia East
          template: ./arm-templates/resourcegroup.json
          parameters: 
            resourceGroupName=rg-githubactions
            location="Australia East"
          deploymentName: rg-githubactions
 
      - name: Deploy Storage account stgithubactions
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscription-id: d64eef0e-d7f1-4c6c-bf8a-9989e7483dd7
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=globostg0432catene2
            location="Australia East"
          deploymentMode: Incremental

      - name: Deploy VM
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscription-id: d64eef0e-d7f1-4c6c-bf8a-9989e7483dd7
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
          deploymentMode: Incremental